INSERT INTO users (active,blocked,deleted, firstName, lastName, passwordHash, username, userRole,email) VALUES (TRUE,FALSE ,FALSE ,'Sinan', 'Sakic', '098f6bcd4621d373cade4e832627b4f6', 'admin', 'ADMINISTRATOR','test7@test.com');
INSERT INTO users (active,blocked,deleted, firstName, lastName, passwordHash, username, userRole,email) VALUES (TRUE,FALSE ,FALSE , 'Jasmin', 'Kaldzija', '098f6bcd4621d373cade4e832627b4f6', 'jkaldzija', 'NORMAL','test2@test.com');
INSERT INTO users (active,blocked,deleted, firstName, lastName, passwordHash, username, userRole,email) VALUES (TRUE,FALSE ,FALSE , 'Alem', 'Zekic', '098f6bcd4621d373cade4e832627b4f6', 'azekic', 'NORMAL','test3@test.com');
INSERT INTO users (active,blocked,deleted, firstName, lastName, passwordHash, username, userRole,email) VALUES (TRUE,FALSE ,FALSE , 'Hamza', 'Semic', '098f6bcd4621d373cade4e832627b4f6', 'hsemic', 'NORMAL','test4@test.com');
INSERT INTO users (active,blocked,deleted, firstName, lastName, passwordHash, username, userRole,email) VALUES (TRUE,FALSE ,FALSE , 'Amna', 'Sukrija', '098f6bcd4621d373cade4e832627b4f6', 'asukrija', 'NORMAL','test5@test.com');
INSERT INTO users (active,blocked,deleted, firstName, lastName, passwordHash, username, userRole,email) VALUES (TRUE,FALSE ,FALSE , 'Irma', 'Kapetanovic', '098f6bcd4621d373cade4e832627b4f6', 'ikapetanovic', 'NORMAL','test6@test.com');

INSERT INTO projects (description, name) VALUES ('Testni projekat', 'Hello world');
INSERT INTO projects (description, name) VALUES ('Projekat sa predmeta NSI', 'PMS-NSI');
INSERT INTO projects (description, name) VALUES ('Testni 3', 'Testni 3');

INSERT INTO projects_users (user_id, project_id, projectRole) VALUES ('1', '1', 'OWNER');
INSERT INTO projects_users (user_id, project_id, projectRole) VALUES ('1', '2', 'MEMBER');
INSERT INTO projects_users (user_id, project_id, projectRole) VALUES ('2', '2', 'OWNER');
INSERT INTO projects_users (user_id, project_id, projectRole) VALUES ('3', '2', 'MEMBER');
INSERT INTO projects_users (user_id, project_id, projectRole) VALUES ('4', '2', 'MEMBER');
INSERT INTO projects_users (user_id, project_id, projectRole) VALUES ('5', '2', 'MEMBER');

INSERT INTO tasks (description, name, project_id, user_id) VALUES ('Hello world task', 'Hello world', '1', '1');
INSERT INTO tasks (description, name, project_id, user_id) VALUES ('MySQL + Hibernate + Java EE7 + Angular', 'Konfiguracija okruženja', '2', '4');
-- INSERT INTO tasks (description, name, project_id, user_id) VALUES ('Kreirati REST servise za osnovne entitete', 'REST servisi', '2', '4');
INSERT INTO tasks (description, name, project_id, user_id) VALUES ('Napisati dokumentaciju za REST servise', 'Dokumentacija API-ja', '2', '5');
INSERT INTO tasks (description, name, project_id, user_id) VALUES ('Napraviti početni Angular View/Controller', 'Konfiguracija Angular frameworka', '2', '3');

INSERT INTO comments (id, text, time_posted, task_id, user_id) VALUES ('1', 'Hello world', NOW(), 1, 1);

INSERT INTO messages ( text, date, sender_id, receiver_id,seen) VALUES ('K''o da si mi neke cini bacila k''o da si me nekako zacarala ne smem drugu da pogledam ubice me grom ako nije sve po tvom Ref. 2x Trezan, a za sebe ne znam trezan, a opijen tobom trezan, k''o na silu vezan ne znam da ti kazem zbogom Ti si mi na zivot tacku stavila najbolje mi drugove zabranila ne druzim se, ne izlazim Boze, vidi me ne znam da joj kazem ne', NOW(), 1, 2,1);
INSERT INTO messages ( text, date, sender_id, receiver_id,seen) VALUES ( 'K''o da si mi neke cini bacila k''o da si me nekako zacarala ne smem drugu da pogledam ubice me grom ako nije sve po tvom Ref. 2x Trezan, a za sebe ne znam trezan, a opijen tobom trezan, k''o na silu vezan ne znam da ti kazem zbogom Ti si mi na zivot tacku stavila najbolje mi drugove zabranila ne druzim se, ne izlazim Boze, vidi me ne znam da joj kazem ne', NOW(), 2, 3,1);
INSERT INTO messages ( text, date, sender_id, receiver_id,seen) VALUES ( 'K''o da si mi neke cini bacila k''o da si me nekako zacarala ne smem drugu da pogledam ubice me grom ako nije sve po tvom Ref. 2x Trezan, a za sebe ne znam trezan, a opijen tobom trezan, k''o na silu vezan ne znam da ti kazem zbogom Ti si mi na zivot tacku stavila najbolje mi drugove zabranila ne druzim se, ne izlazim Boze, vidi me ne znam da joj kazem ne', NOW(), 3, 4,1);
INSERT INTO messages ( text, date, sender_id, receiver_id,seen) VALUES ( 'K''o da si mi neke cini bacila k''o da si me nekako zacarala ne smem drugu da pogledam ubice me grom ako nije sve po tvom Ref. 2x Trezan, a za sebe ne znam trezan, a opijen tobom trezan, k''o na silu vezan ne znam da ti kazem zbogom Ti si mi na zivot tacku stavila najbolje mi drugove zabranila ne druzim se, ne izlazim Boze, vidi me ne znam da joj kazem ne', NOW(), 4, 5,1);
INSERT INTO messages ( text, date, sender_id, receiver_id,seen) VALUES ( 'K''o da si mi neke cini bacila k''o da si me nekako zacarala ne smem drugu da pogledam ubice me grom ako nije sve po tvom Ref. 2x Trezan, a za sebe ne znam trezan, a opijen tobom trezan, k''o na silu vezan ne znam da ti kazem zbogom Ti si mi na zivot tacku stavila najbolje mi drugove zabranila ne druzim se, ne izlazim Boze, vidi me ne znam da joj kazem ne', NOW(), 5, 1,1);
INSERT INTO messages ( text, date, sender_id, receiver_id,seen) VALUES ( 'K''o da si mi neke cini bacila k''o da si me nekako zacarala ne smem drugu da pogledam ubice me grom ako nije sve po tvom Ref. 2x Trezan, a za sebe ne znam trezan, a opijen tobom trezan, k''o na silu vezan ne znam da ti kazem zbogom Ti si mi na zivot tacku stavila najbolje mi drugove zabranila ne druzim se, ne izlazim Boze, vidi me ne znam da joj kazem ne', NOW(), 1, 2,1);
INSERT INTO messages ( text, date, sender_id, receiver_id,seen) VALUES ( 'K''o da si mi neke cini bacila k''o da si me nekako zacarala ne smem drugu da pogledam ubice me grom ako nije sve po tvom Ref. 2x Trezan, a za sebe ne znam trezan, a opijen tobom trezan, k''o na silu vezan ne znam da ti kazem zbogom Ti si mi na zivot tacku stavila najbolje mi drugove zabranila ne druzim se, ne izlazim Boze, vidi me ne znam da joj kazem ne', NOW(), 1, 2,1);
INSERT INTO messages ( text, date, sender_id, receiver_id,seen) VALUES ( 'K''o da si mi neke cini bacila k''o da si me nekako zacarala ne smem drugu da pogledam ubice me grom ako nije sve po tvom Ref. 2x Trezan, a za sebe ne znam trezan, a opijen tobom trezan, k''o na silu vezan ne znam da ti kazem zbogom Ti si mi na zivot tacku stavila najbolje mi drugove zabranila ne druzim se, ne izlazim Boze, vidi me ne znam da joj kazem ne', NOW(), 1, 2,1);
INSERT INTO messages ( text, date, sender_id, receiver_id,seen) VALUES ( 'K''o da si mi neke cini bacila k''o da si me nekako zacarala ne smem drugu da pogledam ubice me grom ako nije sve po tvom Ref. 2x Trezan, a za sebe ne znam trezan, a opijen tobom trezan, k''o na silu vezan ne znam da ti kazem zbogom Ti si mi na zivot tacku stavila najbolje mi drugove zabranila ne druzim se, ne izlazim Boze, vidi me ne znam da joj kazem ne', NOW(), 1, 3,1);
INSERT INTO messages ( text, date, sender_id, receiver_id,seen) VALUES ( 'K''o da si mi neke cini bacila k''o da si me nekako zacarala ne smem drugu da pogledam ubice me grom ako nije sve po tvom Ref. 2x Trezan, a za sebe ne znam trezan, a opijen tobom trezan, k''o na silu vezan ne znam da ti kazem zbogom Ti si mi na zivot tacku stavila najbolje mi drugove zabranila ne druzim se, ne izlazim Boze, vidi me ne znam da joj kazem ne', NOW(), 1, 3,1);
INSERT INTO messages ( text, date, sender_id, receiver_id,seen) VALUES ( 'K''o da si mi neke cini bacila k''o da si me nekako zacarala ne smem drugu da pogledam ubice me grom ako nije sve po tvom Ref. 2x Trezan, a za sebe ne znam trezan, a opijen tobom trezan, k''o na silu vezan ne znam da ti kazem zbogom Ti si mi na zivot tacku stavila najbolje mi drugove zabranila ne druzim se, ne izlazim Boze, vidi me ne znam da joj kazem ne', NOW(), 2, 1,1);
INSERT INTO messages ( text, date, sender_id, receiver_id,seen) VALUES ( 'K''o da si mi neke cini bacila k''o da si me nekako zacarala ne smem drugu da pogledam ubice me grom ako nije sve po tvom Ref. 2x Trezan, a za sebe ne znam trezan, a opijen tobom trezan, k''o na silu vezan ne znam da ti kazem zbogom Ti si mi na zivot tacku stavila najbolje mi drugove zabranila ne druzim se, ne izlazim Boze, vidi me ne znam da joj kazem ne', NOW(), 3, 1,1);
INSERT INTO messages ( text, date, sender_id, receiver_id,seen) VALUES ( 'K''o da si mi neke cini bacila k''o da si me nekako zacarala ne smem drugu da pogledam ubice me grom ako nije sve po tvom Ref. 2x Trezan, a za sebe ne znam trezan, a opijen tobom trezan, k''o na silu vezan ne znam da ti kazem zbogom Ti si mi na zivot tacku stavila najbolje mi drugove zabranila ne druzim se, ne izlazim Boze, vidi me ne znam da joj kazem ne', NOW(), 1, 2,1);
INSERT INTO messages ( text, date, sender_id, receiver_id,seen) VALUES ( 'K''o da si mi neke cini bacila k''o da si me nekako zacarala ne smem drugu da pogledam ubice me grom ako nije sve po tvom Ref. 2x Trezan, a za sebe ne znam trezan, a opijen tobom trezan, k''o na silu vezan ne znam da ti kazem zbogom Ti si mi na zivot tacku stavila najbolje mi drugove zabranila ne druzim se, ne izlazim Boze, vidi me ne znam da joj kazem ne', NOW(), 1, 2,1);